id: I995599D2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:41:50+00:00'
last_modified: '2022-06-08T08:30:15.455074+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23726
  title: གསུང་འབུམ། བློ་བཟང་ཚུལ་ཁྲིམས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EC79:
      image_group_id: I2509
      title: ''
      total_pages: 706
      order: 1
      base_file: EC79.txt
    8F46:
      image_group_id: I2510
      title: ''
      total_pages: 794
      order: 2
      base_file: 8F46.txt
    '2750':
      image_group_id: I2511
      title: ''
      total_pages: 692
      order: 3
      base_file: 2750.txt
    F634:
      image_group_id: I2512
      title: ''
      total_pages: 646
      order: 4
      base_file: F634.txt
    E711:
      image_group_id: I2513
      title: ''
      total_pages: 638
      order: 5
      base_file: E711.txt
    C929:
      image_group_id: I2514
      title: ''
      total_pages: 644
      order: 6
      base_file: C929.txt
    EDB4:
      image_group_id: I2515
      title: ''
      total_pages: 614
      order: 7
      base_file: EDB4.txt
    811C:
      image_group_id: I2516
      title: ''
      total_pages: 690
      order: 8
      base_file: 811C.txt
    C4E7:
      image_group_id: I2517
      title: ''
      total_pages: 444
      order: 9
      base_file: C4E7.txt
    70B4:
      image_group_id: I2518
      title: ''
      total_pages: 548
      order: 10
      base_file: 70B4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
